"""Bundled coding-agent failure claims. Fingerprints are computed, not invented."""

from __future__ import annotations

from datetime import UTC, datetime

from .fingerprint import classify, fingerprint, normalize_error
from .models import Claim, EvalSpec, Fix

_TS = datetime(2026, 8, 1, tzinfo=UTC)

_SEEDS: list[dict] = [
    {
        "id": "spr_a11c000000000001",
        "err": "TypeError: params is a Promise",
        "eco": "npm",
        "rt": "node@20.18.2",
        "dep": ["next@15.0.0"],
        "tried": ["sync-access", "restart"],
        "fix": ("patch", "const { slug } = await params"),
        "eval": "npx tsc --noEmit",
        "note": "Next 15 dynamic APIs are async.",
    },
    {
        "id": "spr_a11c000000000002",
        "err": "TypeError: searchParams is a Promise",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["next@15.0.0"],
        "tried": ["sync-access"],
        "fix": ("patch", "const sp = await searchParams"),
        "eval": "npx tsc --noEmit",
        "note": "Same class as cookies()/headers() in Next 15.",
    },
    {
        "id": "spr_a11c000000000003",
        "err": "ModuleNotFoundError: No module named 'pydantic_core'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["pydantic@2.9.0"],
        "tried": ["pip-install-pydantic"],
        "fix": ("pin", "pydantic>=2.7,<3"),
        "eval": "python -c 'import pydantic'",
    },
    {
        "id": "spr_a11c000000000004",
        "err": "ValidationError: 1 validation error for Model\nurl\n  Field required [type=missing]",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["pydantic@2.8.0"],
        "tried": ["parse_obj"],
        "fix": ("patch", "Model.model_validate(data)  # not parse_obj"),
        "eval": "python -c 'import pydantic'",
    },
    {
        "id": "spr_a11c000000000005",
        "err": "npm ERR! ERESOLVE unable to resolve dependency tree",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["react@19.0.0", "next@15.0.0"],
        "tried": ["npm-install"],
        "fix": ("config", "legacy-peer-deps=true"),
        "eval": "npm ls --depth=0",
    },
    {
        "id": "spr_a11c000000000006",
        "err": "Cannot find module '@/lib/utils' or its corresponding type declarations.",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["typescript@5.6.0"],
        "tried": ["relative-import"],
        "fix": ("config", '{"compilerOptions":{"baseUrl":".","paths":{"@/*":["./src/*"]}}}'),
        "eval": "npx tsc --noEmit",
    },
    {
        "id": "spr_a11c000000000007",
        "err": "browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium",
        "eco": "browser",
        "rt": "node@20",
        "dep": ["playwright@1.48.0"],
        "tried": ["npm-install"],
        "fix": ("cmd", "npx playwright install --with-deps chromium"),
        "eval": "npx playwright --version",
    },
    {
        "id": "spr_a11c000000000008",
        "err": 'ZodError: Required at "email"',
        "eco": "npm",
        "rt": "node@20",
        "dep": ["zod@3.23.0"],
        "tried": ["optional-field"],
        "fix": ("patch", "email: z.string().email()"),
        "eval": "npx tsc --noEmit",
    },
    {
        "id": "spr_a11c00000000000a",
        "err": "StripeInvalidRequestError: Invalid API version",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["stripe@16.0.0"],
        "tried": ["latest-sdk"],
        "fix": ("pin", "apiVersion: '2024-06-20'"),
        "eval": "node -e \"require('stripe')\"",
    },
    {
        "id": "spr_a11c00000000000c",
        "err": "ModuleNotFoundError: No module named 'src'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": [],
        "tried": ["sys-path-hack"],
        "fix": ("config", "pip install -e ."),
        "eval": 'python -c "import src"',
    },
    {
        "id": "spr_a11c00000000000d",
        "err": "TypeError: useFormState is not exported from 'react-dom'",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["react@19.0.0", "react-dom@19.0.0"],
        "tried": ["react-dom-import"],
        "fix": ("patch", "import { useActionState } from 'react'"),
        "eval": "npx tsc --noEmit",
        "note": "useFormState is exported on react-dom 19.0+; RC-era fingerprint. Prefer useActionState from react.",
    },
    {
        "id": "spr_a11c00000000000e",
        "err": "CssSyntaxError: @tailwind is not a known at-rule",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["tailwindcss@4.0.0"],
        "tried": ["postcss-config"],
        "fix": ("patch", '@import "tailwindcss";'),
        "eval": "npx tailwindcss --help",
        "note": "@tailwind at-rule is stylelint/language-service, not tailwindcss 4 CLI.",
    },
    {
        "id": "spr_a11c00000000000f",
        "err": "go: verifying module: checksum mismatch",
        "eco": "go",
        "rt": "go@1.23",
        "dep": [],
        "tried": ["go-clean-modcache"],
        "fix": ("cmd", "go clean -modcache && go mod download"),
        "eval": "go mod verify",
    },
    {
        "id": "spr_a11c000000000011",
        "err": "Error: Cannot find module 'next/headers' from '/app/src/app/page.tsx'",
        "eco": "npm",
        "rt": "node@18",
        "dep": ["next@13.5.0"],
        "tried": ["pages-router-import"],
        "fix": ("constraint", "next/headers only exists in the app router"),
        "eval": "npx next build",
    },
    {
        "id": "spr_a11c000000000014",
        "err": "ImportError: cannot import name 'BaseSettings' from 'pydantic'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["pydantic@2.0.0"],
        "tried": ["from pydantic import BaseSettings"],
        "fix": ("patch", "from pydantic_settings import BaseSettings"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('pydantic')!='2.0.0')\"",
        "note": "Moved in pydantic v2.",
    },
    {
        "id": "spr_a11c000000000018",
        "err": "ModuleNotFoundError: No module named 'cgi'",
        "eco": "py",
        "rt": "py@3.13",
        "dep": [],
        "tried": ["import cgi"],
        "fix": ("constraint", "cgi was removed in 3.13; use email.message / multipart"),
        "eval": 'python -c "import cgi"',
    },
    {
        "id": "spr_a11c00000000001a",
        "err": "You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["openai@1.0.0"],
        "tried": ["openai.ChatCompletion.create"],
        "fix": ("patch", "client.chat.completions.create(...)"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('openai')!='1.0.0')\"",
    },
    {
        "id": "spr_a11c00000000001f",
        "err": "ReferenceError: fetch is not defined",
        "eco": "npm",
        "rt": "node@16",
        "dep": [],
        "tried": ["window-fetch"],
        "fix": ("pin", "Node 18+ has fetch, or npm install undici"),
        "eval": "node -e \"require('Node 18+ has fetch, or npm install undici')\"",
    },
    {
        "id": "spr_a11c000000000020",
        "err": "Error: Invalid src prop on next/image, hostname is not configured under images",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["next@15.0.0"],
        "tried": ["img-tag"],
        "fix": ("config", "images.remotePatterns in next.config"),
        "eval": "node -e \"if(require('next/package.json').version!=='15.0.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000021",
        "err": "StripeSignatureVerificationError: No signatures found matching the expected signature for payload",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["stripe@16.0.0"],
        "tried": ["JSON.stringify-body"],
        "fix": ("constraint", "verify with the raw request body, not parsed JSON"),
        "eval": "node -e \"if(require('stripe/package.json').version!=='16.0.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000023",
        "err": "ImportError: cannot import name 'LLMChain' from 'langchain'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["langchain@0.2.0"],
        "tried": ["from langchain import LLMChain"],
        "fix": ("patch", "from langchain.chains.llm import LLMChain"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('langchain')!='0.2.0')\"",
        "note": "No langchain version satisfies both halves: 0.1-0.3 root import works; 1.0 has no langchain.chains.",
    },
    {
        "id": "spr_a11c000000000024",
        "err": "Named export 'foo' not found. The requested module is a CommonJS module",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["vite@5.0.0"],
        "tried": ["named-esm-import"],
        "fix": ("patch", "import pkg from 'cjs-lib'; pkg.foo"),
        "eval": "node -e \"if(require('vite/package.json').version!=='5.0.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000025",
        "err": 'Error: Route "/" used `cookies().get`. `cookies()` was called outside a Request Scope',
        "eco": "npm",
        "rt": "node@20",
        "dep": ["next@15.0.0"],
        "tried": ["cookies-sync"],
        "fix": ("patch", "const jar = await cookies()"),
        "eval": "node -e \"if(require('next/package.json').version!=='15.0.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000026",
        "err": "OSError: You are trying to access a gated repo",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["huggingface_hub"],
        "tried": ["from_pretrained"],
        "fix": ("constraint", "huggingface-cli login, then accept the model terms on the hub"),
        "eval": 'python -c "import huggingface_hub"',
    },
    {
        "id": "spr_a11c000000000027",
        "err": "ImportError: cannot import name 'ChatOpenAI' from 'langchain.chat_models'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["langchain@1.0.0"],
        "tried": ["from langchain.chat_models import ChatOpenAI"],
        "fix": ("patch", "from langchain_openai import ChatOpenAI"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('langchain')!='1.0.0')\"",
        "note": "LangChain 1.0 removed top-level re-exports.",
    },
    {
        "id": "spr_a11c000000000028",
        "err": "ModuleNotFoundError: No module named 'langchain_openai'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["langchain@1.0.0"],
        "tried": ["pip-install-langchain"],
        "fix": ("pin", "pip install langchain-openai"),
        "eval": 'python -c "import langchain_openai"',
    },
    {
        "id": "spr_a11c000000000029",
        "err": "ImportError: cannot import name 'OpenAI' from 'langchain.llms'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["langchain@0.2.0"],
        "tried": ["from langchain.llms import OpenAI"],
        "fix": ("patch", "from langchain_openai import ChatOpenAI"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('langchain')!='0.2.0')\"",
    },
    {
        "id": "spr_a11c00000000002a",
        "err": "ModuleNotFoundError: No module named 'llama_index.core'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["llama-index"],
        "tried": ["pip-install-llama-index"],
        "fix": ("pin", "pip install llama-index-core"),
        "eval": 'python -c "import llama_index.core"',
    },
    {
        "id": "spr_a11c00000000002b",
        "err": "ImportError: cannot import name 'VectorStoreIndex' from 'llama_index'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["llama-index@0.10.0"],
        "tried": ["from llama_index import VectorStoreIndex"],
        "fix": ("patch", "from llama_index.core import VectorStoreIndex"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('llama-index')!='0.10.0')\"",
    },
    {
        "id": "spr_a11c00000000002c",
        "err": "ModuleNotFoundError: No module named 'distutils'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["crewai"],
        "tried": ["import distutils"],
        "fix": ("pin", "pip install setuptools  # distutils removed in Python 3.12"),
        "eval": 'python -c "import distutils"',
    },
    {
        "id": "spr_a11c00000000002d",
        "err": "ModuleNotFoundError: No module named 'mcp.server.fastmcp'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["mcp@2.0.0"],
        "tried": ["from mcp.server.fastmcp import FastMCP"],
        "fix": ("patch", "from mcp.server import MCPServer  # FastMCP renamed in MCP Python SDK v2"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('mcp')!='2.0.0')\"",
    },
    {
        "id": "spr_a11c00000000002e",
        "err": "ImportError: cannot import name 'McpError' from 'mcp'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["mcp@2.0.0"],
        "tried": ["from mcp import McpError"],
        "fix": ("patch", "from mcp import MCPError"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('mcp')!='2.0.0')\"",
    },
    {
        "id": "spr_a11c000000000031",
        "err": "error:0308010C:digital envelope routines::unsupported",
        "eco": "npm",
        "rt": "node@18",
        "dep": ["webpack@4"],
        "tried": ["webpack-openssl"],
        "fix": ("constraint", "Node 17+ OpenSSL 3. Set NODE_OPTIONS=--openssl-legacy-provider or upgrade webpack."),
        "eval": "node -e \"if(require('webpack/package.json').version!=='4') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000033",
        "err": "Hydration failed because the initial UI does not match what was rendered on the server",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["next@15.0.0", "react@19.0.0"],
        "tried": ["suppressHydrationWarning"],
        "fix": ("constraint", "Server HTML must match client. Do not use window, Date.now, or Math.random during render."),
        "eval": "node -e \"if(require('next/package.json').version!=='15.0.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000034",
        "err": "Error: Cannot find module 'crypto'",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["webpack@5"],
        "tried": ["node-polyfill"],
        "fix": ("constraint", "Webpack 5 does not polyfill Node builtins. Use Web Crypto or resolve.fallback."),
        "eval": "node -e \"if(require('webpack/package.json').version!=='5') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000035",
        "err": "PrismaClientInitializationError: Can't reach database server",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["prisma"],
        "tried": ["prisma-generate"],
        "fix": ("constraint", "DATABASE_URL is wrong or the database is not running."),
        "eval": "node -e \"require('prisma')\"",
    },
    {
        "id": "spr_a11c000000000036",
        "err": "[next-auth]: `NEXTAUTH_SECRET` missing",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["next-auth@4"],
        "tried": ["next-auth-no-env"],
        "fix": ("config", "Set NEXTAUTH_SECRET (Auth.js: AUTH_SECRET) in the environment, never in client code."),
        "eval": "node -e \"if(require('next-auth/package.json').version!=='4') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000037",
        "err": "RuntimeError: CUDA out of memory",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["torch"],
        "tried": ["batch-size-default"],
        "fix": ("constraint", "Lower batch size or run on CPU. Do not retry the same batch."),
        "eval": 'python -c "import torch"',
    },
    {
        "id": "spr_a11c000000000038",
        "err": "openai.BadRequestError: Error code: 400 - context_length_exceeded",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["openai@1.0.0"],
        "tried": ["full-history"],
        "fix": ("constraint", "Trim messages and tools until the prompt fits. Do not retry the same payload."),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('openai')!='1.0.0')\"",
    },
    {
        "id": "spr_a11c00000000003e",
        "err": "AttributeError: 'Engine' object has no attribute 'execute'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["sqlalchemy@2.0.0"],
        "tried": ["engine.execute"],
        "fix": ("patch", "with engine.connect() as conn: conn.execute(text(sql))  # SQLAlchemy 2"),
        "eval": "python -c \"from importlib.metadata import version; raise SystemExit(version('sqlalchemy')!='2.0.0')\"",
    },
    {
        "id": "spr_a11c000000000041",
        "err": "anthropic.RateLimitError: Error code: 429",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["anthropic"],
        "tried": ["retry-immediate"],
        "fix": ("constraint", "Back off. Do not tight-loop the same request. Use retry-after if present."),
        "eval": 'python -c "import anthropic"',
    },
    {
        "id": "spr_a11c000000000042",
        "err": "KeyError: 'OPENAI_API_KEY'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["openai"],
        "tried": ["os.environ-bare"],
        "fix": ("constraint", "The process does not have OPENAI_API_KEY. Set it in the environment the agent actually runs in."),
        "eval": 'python -c "import openai"',
    },
    {
        "id": "spr_a11c000000000044",
        "err": "ReferenceError: process is not defined",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["vite@5.0.0"],
        "tried": ["process.env-in-browser"],
        "fix": ("constraint", "Browser bundles have no process. Use import.meta.env (Vite) or NEXT_PUBLIC_ vars."),
        "eval": "node -e \"if(require('vite/package.json').version!=='5.0.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000045",
        "err": "Error: Could not find a production build in the '.next' directory",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["next@15.0.0"],
        "tried": ["next-start-no-build"],
        "fix": ("cmd", "npx next build"),
        "eval": "node -e \"if(require('next/package.json').version!=='15.0.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c00000000004c",
        "err": "huggingface_hub.utils.HfHubHTTPError: 401 Client Error",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["huggingface_hub"],
        "tried": ["from_pretrained"],
        "fix": ("constraint", "Missing or invalid HF token. huggingface-cli login, or set HF_TOKEN."),
        "eval": 'python -c "import huggingface_hub"',
    },
    {
        "id": "spr_a11c00000000004d",
        "err": "Can't resolve 'buffer' in",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["webpack@5"],
        "tried": ["node-buffer"],
        "fix": ("constraint", "Webpack 5 dropped Node polyfills. Add resolve.fallback.buffer or stop importing Node libs in the browser."),
        "eval": "node -e \"if(require('webpack/package.json').version!=='5') process.exit(1)\"",
    },
    {
        "id": "spr_a11c00000000004e",
        "err": "django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["django"],
        "tried": ["import-models"],
        "fix": ("constraint", "Set DJANGO_SETTINGS_MODULE before importing Django models, or call django.setup()."),
        "eval": 'python -c "import django"',
    },
    {
        "id": "spr_a11c000000000050",
        "err": "uv: No solution found when resolving dependencies",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["uv"],
        "tried": ["uv-add"],
        "fix": ("constraint", "Two packages pin incompatible versions. Relax a pin, or drop one of the packages. CrewAI vs langchain-openai is a common pair."),
        "eval": 'python -c "import uv"',
    },
    {
        "id": "spr_a11c000000000053",
        "err": "ModuleNotFoundError: No module named 'pkg_resources'",
        "eco": "py",
        "rt": "py@3.12",
        "dep": [],
        "tried": ["import pkg_resources"],
        "fix": ("pin", "pip install setuptools"),
        "eval": 'python -c "import pkg_resources"',
        "note": "setuptools 84 dropped pkg_resources; pin setuptools<81. See cix_5e3965fdc7fed2d5.",
    },
    {
        "id": "spr_a11c000000000054",
        "err": "RuntimeError: Working outside of application context",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["flask"],
        "tried": ["current_app"],
        "fix": ("patch", "Use the app context: with app.app_context(): ..."),
        "eval": 'python -c "import flask"',
    },
    {
        "id": "spr_a11c000000000055",
        "err": "google.api_core.exceptions.ResourceExhausted: 429",
        "eco": "py",
        "rt": "py@3.12",
        "dep": ["google-generativeai"],
        "tried": ["retry-immediate"],
        "fix": ("constraint", "Quota. Back off. Do not tight-loop. Switch model or billing if the quota is exhausted."),
        "eval": 'python -c "import google_generativeai"',
    },
    {
        "id": "spr_a11c000000000056",
        "err": "Error: Cannot find module 'sharp'",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["next@15.0.0"],
        "tried": ["next-image"],
        "fix": ("pin", "npm install sharp  # required for next/image in standalone/CI"),
        "eval": "node -e \"require('npm install sharp  # required for next/image in standalone/CI')\"",
    },
    {
        "id": "spr_a11c000000000057",
        "err": "error TS2304: Cannot find name 'React'",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["typescript@5.6.0"],
        "tried": ["react-without-types"],
        "fix": ("config", "jsx: react-jsx, and install @types/react. Do not prefix every JSX file with import React from 'react' unless jsx is react."),
        "eval": "node -e \"if(require('typescript/package.json').version!=='5.6.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000059",
        "err": "Ollama: model not found",
        "eco": "other",
        "rt": "",
        "dep": ["ollama"],
        "tried": ["chat-missing-model"],
        "fix": ("constraint", "The model is not on disk. ollama pull <name>, then retry. Do not change the name and hope."),
        "eval": 'python -c "import ollama"',
    },
    {
        "id": "spr_a11c00000000005c",
        "err": "Error: connect ECONNREFUSED 127.0.0.1:5432",
        "eco": "other",
        "rt": "",
        "dep": ["postgres"],
        "tried": ["app-before-db"],
        "fix": ("constraint", "Nothing is listening on that port. Start Postgres, or point DATABASE_URL at a host that is actually up."),
        "eval": 'python -c "import postgres"',
    },
    {
        "id": "spr_a11c000000000060",
        "err": "Cannot use JSX unless the '--jsx' flag is provided",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["typescript@5.6.0"],
        "tried": ["tsx-without-jsx"],
        "fix": ("config", "compilerOptions.jsx = 'react-jsx' in tsconfig. Include the file in tsconfig include."),
        "eval": "node -e \"if(require('typescript/package.json').version!=='5.6.0') process.exit(1)\"",
    },
    {
        "id": "spr_a11c000000000061",
        "err": "Error: Cannot find native binding",
        "eco": "npm",
        "rt": "node@20",
        "dep": ["@swc/core"],
        "tried": ["npm-install"],
        "fix": (
            "constraint",
            "Optional native binary missing for this platform. Reinstall the package on this OS/arch, or delete node_modules and lockfile then npm ci.",
        ),
        "eval": "node -e \"require('@swc/core')\"",
    },
    {
        "id": "spr_a11c000000000064",
        "err": "Unable to locate credentials",
        "eco": "other",
        "rt": "",
        "dep": ["boto3"],
        "tried": ["aws-sdk"],
        "fix": (
            "constraint",
            "No AWS credentials in this process. Set AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY or a profile, in the environment the agent actually runs.",
        ),
        "eval": 'python -c "import boto3"',
    },
]


def materialize() -> list[Claim]:
    out: list[Claim] = []
    for raw in _SEEDS:
        err = raw["err"]
        cls = classify(err)
        dep = list(raw.get("dep") or [])
        eco = raw.get("eco") or "other"
        rt = raw.get("rt") or ""
        k, b = raw["fix"]
        out.append(
            Claim(
                id=raw["id"],
                fp=fingerprint(err=err, cls=cls, eco=eco, rt=rt, dep=dep),
                cls=cls,
                err=normalize_error(err),
                eco=eco,
                rt=rt,
                dep=dep,
                tried=list(raw.get("tried") or []),
                fix=Fix(k=k, b=b),
                eval=EvalSpec(cmd=raw["eval"]),
                st=raw.get("st") or "proposed",
                nc=int(raw.get("nc") or 0),
                nf=int(raw.get("nf") or 0),
                own="did:claimidx:seed",
                ts=_TS,
                note=raw.get("note") or "",
                src="seed",
            )
        )
    return out
