"""Bundled coding-agent failure claims. Fingerprints are computed, not invented."""

from __future__ import annotations

from datetime import datetime, timezone

from .fingerprint import classify, fingerprint, normalize_error
from .models import Claim, EvalSpec, Fix

_TS = datetime(2026, 8, 1, tzinfo=timezone.utc)

_SEEDS: list[dict] = [
    {"id": "spr_a11c000000000001", "err": "TypeError: params is a Promise", "eco": "npm", "rt": "node@20.18.2", "dep": ["next@15.0.0"], "tried": ["sync-access", "restart"], "fix": ("patch", "const { slug } = await params"), "eval": "npx tsc --noEmit", "st": "confirmed", "nc": 11, "nf": 1, "note": "Next 15 dynamic APIs are async."},
    {"id": "spr_a11c000000000002", "err": "TypeError: searchParams is a Promise", "eco": "npm", "rt": "node@20", "dep": ["next@15.0.0"], "tried": ["sync-access"], "fix": ("patch", "const sp = await searchParams"), "eval": "npx tsc --noEmit", "st": "confirmed", "nc": 7, "nf": 0, "note": "Same class as cookies()/headers() in Next 15."},
    {"id": "spr_a11c000000000003", "err": "ModuleNotFoundError: No module named 'pydantic_core'", "eco": "py", "rt": "py@3.12", "dep": ["pydantic@2.9.0"], "tried": ["pip-install-pydantic"], "fix": ("pin", "pydantic>=2.7,<3"), "eval": "python -c 'import pydantic'", "st": "confirmed", "nc": 4, "nf": 0},
    {"id": "spr_a11c000000000004", "err": "ValidationError: 1 validation error for Model\nurl\n  Field required [type=missing]", "eco": "py", "rt": "py@3.12", "dep": ["pydantic@2.8.0"], "tried": ["parse_obj"], "fix": ("patch", "Model.model_validate(data)  # not parse_obj"), "eval": "python -c 'import pydantic'", "st": "confirmed", "nc": 9, "nf": 1},
    {"id": "spr_a11c000000000005", "err": "npm ERR! ERESOLVE unable to resolve dependency tree", "eco": "npm", "rt": "node@20", "dep": ["react@19.0.0", "next@15.0.0"], "tried": ["npm-install"], "fix": ("config", "legacy-peer-deps=true"), "eval": "npm ls --depth=0", "st": "confirmed", "nc": 6, "nf": 2},
    {"id": "spr_a11c000000000006", "err": "Cannot find module '@/lib/utils' or its corresponding type declarations.", "eco": "npm", "rt": "node@20", "dep": ["typescript@5.6.0"], "tried": ["relative-import"], "fix": ("config", '{"compilerOptions":{"baseUrl":".","paths":{"@/*":["./src/*"]}}}'), "eval": "npx tsc --noEmit", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000007", "err": "browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium", "eco": "browser", "rt": "node@20", "dep": ["playwright@1.48.0"], "tried": ["npm-install"], "fix": ("cmd", "npx playwright install --with-deps chromium"), "eval": "npx playwright --version", "st": "confirmed", "nc": 12, "nf": 0},
    {"id": "spr_a11c000000000008", "err": "ZodError: Required at \"email\"", "eco": "npm", "rt": "node@20", "dep": ["zod@3.23.0"], "tried": ["optional-field"], "fix": ("patch", "email: z.string().email()"), "eval": "npx tsc --noEmit", "st": "proposed", "nc": 1, "nf": 0},
    {"id": "spr_a11c000000000009", "err": "Error: 429 Too Many Requests — rate limit exceeded", "eco": "other", "rt": "", "dep": [], "tried": ["retry-immediate"], "fix": ("cmd", "sleep $((2 ** attempt)) && retry"), "eval": "true", "st": "confirmed", "nc": 5, "nf": 1},
    {"id": "spr_a11c00000000000a", "err": "StripeInvalidRequestError: Invalid API version", "eco": "npm", "rt": "node@20", "dep": ["stripe@16.0.0"], "tried": ["latest-sdk"], "fix": ("pin", "apiVersion: '2024-06-20'"), "eval": "node -e \"require('stripe')\"", "st": "confirmed", "nc": 3, "nf": 0},
    {"id": "spr_a11c00000000000b", "err": "Error: MCP error -32601: Method not found: tools/list", "eco": "mcp", "rt": "node@20", "dep": [], "tried": ["tools.list"], "fix": ("constraint", "speak JSON-RPC method tools/list after initialize"), "eval": "true", "st": "confirmed", "nc": 4, "nf": 0},
    {"id": "spr_a11c00000000000c", "err": "ModuleNotFoundError: No module named 'src'", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["sys-path-hack"], "fix": ("config", "pip install -e ."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 1},
    {"id": "spr_a11c00000000000d", "err": "TypeError: useFormState is not exported from 'react-dom'", "eco": "npm", "rt": "node@20", "dep": ["react@19.0.0", "react-dom@19.0.0"], "tried": ["react-dom-import"], "fix": ("patch", "import { useActionState } from 'react'"), "eval": "npx tsc --noEmit", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c00000000000e", "err": "CssSyntaxError: @tailwind is not a known at-rule", "eco": "npm", "rt": "node@20", "dep": ["tailwindcss@4.0.0"], "tried": ["postcss-config"], "fix": ("patch", '@import "tailwindcss";'), "eval": "npx tailwindcss --help", "st": "confirmed", "nc": 4, "nf": 0},
    {"id": "spr_a11c00000000000f", "err": "go: verifying module: checksum mismatch", "eco": "go", "rt": "go@1.23", "dep": [], "tried": ["go-clean-modcache"], "fix": ("cmd", "go clean -modcache && go mod download"), "eval": "go mod verify", "st": "proposed", "nc": 2, "nf": 1},
    {"id": "spr_a11c000000000010", "err": "PermissionError: [Errno 13] Permission denied: '/usr/local/lib'", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["sudo-pip"], "fix": ("cmd", "python -m venv .venv && .venv/bin/pip install -e ."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000011", "err": "Error: Cannot find module 'next/headers' from '/app/src/app/page.tsx'", "eco": "npm", "rt": "node@18", "dep": ["next@13.5.0"], "tried": ["pages-router-import"], "fix": ("constraint", "next/headers only exists in the app router"), "eval": "npx next build", "st": "contested", "nc": 1, "nf": 3},
    {"id": "spr_a11c000000000012", "err": "HTTP 200 OK but body is {\"error\":\"invalid_request\"}", "eco": "other", "rt": "", "dep": [], "tried": ["trust-status"], "fix": ("constraint", "do not treat HTTP 200 as success; parse body.error"), "eval": "true", "st": "confirmed", "nc": 3, "nf": 0},
    {"id": "spr_a11c000000000013", "err": "AttributeError: type object 'datetime.datetime' has no attribute 'utcnow'", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["datetime.utcnow"], "fix": ("patch", "datetime.now(timezone.utc)  # utcnow removed"), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0, "note": "Python 3.12+."},
    {"id": "spr_a11c000000000014", "err": "ImportError: cannot import name 'BaseSettings' from 'pydantic'", "eco": "py", "rt": "py@3.12", "dep": ["pydantic@2.0.0"], "tried": ["from pydantic import BaseSettings"], "fix": ("patch", "from pydantic_settings import BaseSettings"), "eval": "true", "st": "confirmed", "nc": 10, "nf": 1, "note": "Moved in pydantic v2."},
    {"id": "spr_a11c000000000015", "err": "ImportError: HTTPX is required to use TestClient", "eco": "py", "rt": "py@3.12", "dep": ["starlette@0.41.0"], "tried": ["starlette.testclient"], "fix": ("pin", "httpx>=0.27"), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c000000000016", "err": "TypeError: Client.__init__() got an unexpected keyword argument 'app'", "eco": "py", "rt": "py@3.13", "dep": ["httpx@0.28.0", "starlette@0.41.0"], "tried": ["TestClient"], "fix": ("pin", "Use httpx 0.27 or a Starlette that speaks httpx 0.28 (httpx2 extra)"), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c000000000017", "err": "SyntaxError: f-string expression part cannot include a backslash", "eco": "py", "rt": "py@3.11", "dep": [], "tried": ["backslash-in-fstring"], "fix": ("patch", "Assign the expression to a name, then interpolate the name."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000018", "err": "ModuleNotFoundError: No module named 'cgi'", "eco": "py", "rt": "py@3.13", "dep": [], "tried": ["import cgi"], "fix": ("constraint", "cgi was removed in 3.13; use email.message / multipart"), "eval": "true", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c000000000019", "err": "ReferenceError: __dirname is not defined in ES module scope", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["__dirname"], "fix": ("patch", "import { fileURLToPath } from 'url'; const __dirname = fileURLToPath(new URL('.', import.meta.url))"), "eval": "true", "st": "confirmed", "nc": 11, "nf": 0},
    {"id": "spr_a11c00000000001a", "err": "You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0", "eco": "py", "rt": "py@3.12", "dep": ["openai@1.0.0"], "tried": ["openai.ChatCompletion.create"], "fix": ("patch", "client.chat.completions.create(...)"), "eval": "true", "st": "confirmed", "nc": 14, "nf": 1},
    {"id": "spr_a11c00000000001b", "err": "SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["disable-verify"], "fix": ("pin", "pip install certifi and set SSL_CERT_FILE to certifi.where()"), "eval": "true", "st": "confirmed", "nc": 8, "nf": 2},
    {"id": "spr_a11c00000000001c", "err": "Error: listen EADDRINUSE: address already in use :::3000", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["restart"], "fix": ("constraint", "Another process owns the port. Free it or set PORT to an unused one."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c00000000001d", "err": "npm ERR! enoent ENOENT: no such file or directory, open 'package.json'", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["npm-install-wrong-dir"], "fix": ("constraint", "cd to the package root that actually contains package.json"), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c00000000001e", "err": "Failed: async def functions are not natively supported. You may need pytest-asyncio", "eco": "py", "rt": "py@3.12", "dep": ["pytest@8.0.0"], "tried": ["pytest-async-def"], "fix": ("pin", "pytest-asyncio and asyncio_mode=auto"), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c00000000001f", "err": "ReferenceError: fetch is not defined", "eco": "npm", "rt": "node@16", "dep": [], "tried": ["window-fetch"], "fix": ("pin", "Node 18+ has fetch, or npm install undici"), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000020", "err": "Error: Invalid src prop on next/image, hostname is not configured under images", "eco": "npm", "rt": "node@20", "dep": ["next@15.0.0"], "tried": ["img-tag"], "fix": ("config", "images.remotePatterns in next.config"), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c000000000021", "err": "StripeSignatureVerificationError: No signatures found matching the expected signature for payload", "eco": "npm", "rt": "node@20", "dep": ["stripe@16.0.0"], "tried": ["JSON.stringify-body"], "fix": ("constraint", "verify with the raw request body, not parsed JSON"), "eval": "true", "st": "confirmed", "nc": 7, "nf": 1},
    {"id": "spr_a11c000000000022", "err": "The token '&&' is not a valid statement separator in this version.", "eco": "other", "rt": "windows", "dep": [], "tried": ["bash-and-and"], "fix": ("constraint", "Windows PowerShell 5: use ; not &&. PowerShell 7 accepts &&."), "eval": "true", "st": "confirmed", "nc": 12, "nf": 0},
    {"id": "spr_a11c000000000023", "err": "ImportError: cannot import name 'LLMChain' from 'langchain'", "eco": "py", "rt": "py@3.12", "dep": ["langchain@0.2.0"], "tried": ["from langchain import LLMChain"], "fix": ("patch", "from langchain.chains.llm import LLMChain"), "eval": "true", "st": "confirmed", "nc": 5, "nf": 2},
    {"id": "spr_a11c000000000024", "err": "Named export 'foo' not found. The requested module is a CommonJS module", "eco": "npm", "rt": "node@20", "dep": ["vite@5.0.0"], "tried": ["named-esm-import"], "fix": ("patch", "import pkg from 'cjs-lib'; pkg.foo"), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000025", "err": "Error: Route \"/\" used `cookies().get`. `cookies()` was called outside a Request Scope", "eco": "npm", "rt": "node@20", "dep": ["next@15.0.0"], "tried": ["cookies-sync"], "fix": ("patch", "const jar = await cookies()"), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c000000000026", "err": "OSError: You are trying to access a gated repo", "eco": "py", "rt": "py@3.12", "dep": ["huggingface_hub"], "tried": ["from_pretrained"], "fix": ("constraint", "huggingface-cli login, then accept the model terms on the hub"), "eval": "true", "st": "confirmed", "nc": 4, "nf": 0},
    {"id": "spr_a11c000000000027", "err": "ImportError: cannot import name 'ChatOpenAI' from 'langchain.chat_models'", "eco": "py", "rt": "py@3.12", "dep": ["langchain@1.0.0"], "tried": ["from langchain.chat_models import ChatOpenAI"], "fix": ("patch", "from langchain_openai import ChatOpenAI"), "eval": "true", "st": "confirmed", "nc": 18, "nf": 1, "note": "LangChain 1.0 removed top-level re-exports."},
    {"id": "spr_a11c000000000028", "err": "ModuleNotFoundError: No module named 'langchain_openai'", "eco": "py", "rt": "py@3.12", "dep": ["langchain@1.0.0"], "tried": ["pip-install-langchain"], "fix": ("pin", "pip install langchain-openai"), "eval": "true", "st": "confirmed", "nc": 15, "nf": 0},
    {"id": "spr_a11c000000000029", "err": "ImportError: cannot import name 'OpenAI' from 'langchain.llms'", "eco": "py", "rt": "py@3.12", "dep": ["langchain@0.2.0"], "tried": ["from langchain.llms import OpenAI"], "fix": ("patch", "from langchain_openai import ChatOpenAI"), "eval": "true", "st": "confirmed", "nc": 12, "nf": 1},
    {"id": "spr_a11c00000000002a", "err": "ModuleNotFoundError: No module named 'llama_index.core'", "eco": "py", "rt": "py@3.12", "dep": ["llama-index"], "tried": ["pip-install-llama-index"], "fix": ("pin", "pip install llama-index-core"), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c00000000002b", "err": "ImportError: cannot import name 'VectorStoreIndex' from 'llama_index'", "eco": "py", "rt": "py@3.12", "dep": ["llama-index@0.10.0"], "tried": ["from llama_index import VectorStoreIndex"], "fix": ("patch", "from llama_index.core import VectorStoreIndex"), "eval": "true", "st": "confirmed", "nc": 11, "nf": 1},
    {"id": "spr_a11c00000000002c", "err": "ModuleNotFoundError: No module named 'distutils'", "eco": "py", "rt": "py@3.12", "dep": ["crewai"], "tried": ["import distutils"], "fix": ("pin", "pip install setuptools  # distutils removed in Python 3.12"), "eval": "true", "st": "confirmed", "nc": 10, "nf": 0},
    {"id": "spr_a11c00000000002d", "err": "ModuleNotFoundError: No module named 'mcp.server.fastmcp'", "eco": "py", "rt": "py@3.12", "dep": ["mcp@2.0.0"], "tried": ["from mcp.server.fastmcp import FastMCP"], "fix": ("patch", "from mcp.server import MCPServer  # FastMCP renamed in MCP Python SDK v2"), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c00000000002e", "err": "ImportError: cannot import name 'McpError' from 'mcp'", "eco": "py", "rt": "py@3.12", "dep": ["mcp@2.0.0"], "tried": ["from mcp import McpError"], "fix": ("patch", "from mcp import MCPError"), "eval": "true", "st": "confirmed", "nc": 4, "nf": 0},
    {"id": "spr_a11c00000000002f", "err": "Error [ERR_REQUIRE_ESM]: require() of ES Module", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["require-esm"], "fix": ("constraint", "Use import, or dynamic import(), or a CJS build. Do not require() a pure ESM package."), "eval": "true", "st": "confirmed", "nc": 16, "nf": 1},
    {"id": "spr_a11c000000000030", "err": "SyntaxError: Cannot use import statement outside a module", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["import-without-type-module"], "fix": ("config", '{"type":"module"} in package.json, or rename to .mjs'), "eval": "true", "st": "confirmed", "nc": 14, "nf": 0},
    {"id": "spr_a11c000000000031", "err": "error:0308010C:digital envelope routines::unsupported", "eco": "npm", "rt": "node@18", "dep": ["webpack@4"], "tried": ["webpack-openssl"], "fix": ("constraint", "Node 17+ OpenSSL 3. Set NODE_OPTIONS=--openssl-legacy-provider or upgrade webpack."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 1},
    {"id": "spr_a11c000000000032", "err": "FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["default-heap"], "fix": ("constraint", "Raise V8 heap: NODE_OPTIONS=--max-old-space-size=4096. Do not retry the same Node process."), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c000000000033", "err": "Hydration failed because the initial UI does not match what was rendered on the server", "eco": "npm", "rt": "node@20", "dep": ["next@15.0.0", "react@19.0.0"], "tried": ["suppressHydrationWarning"], "fix": ("constraint", "Server HTML must match client. Do not use window, Date.now, or Math.random during render."), "eval": "true", "st": "confirmed", "nc": 13, "nf": 1},
    {"id": "spr_a11c000000000034", "err": "Error: Cannot find module 'crypto'", "eco": "npm", "rt": "node@20", "dep": ["webpack@5"], "tried": ["node-polyfill"], "fix": ("constraint", "Webpack 5 does not polyfill Node builtins. Use Web Crypto or resolve.fallback."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000035", "err": "PrismaClientInitializationError: Can't reach database server", "eco": "npm", "rt": "node@20", "dep": ["prisma"], "tried": ["prisma-generate"], "fix": ("constraint", "DATABASE_URL is wrong or the database is not running."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000036", "err": "[next-auth]: `NEXTAUTH_SECRET` missing", "eco": "npm", "rt": "node@20", "dep": ["next-auth@4"], "tried": ["next-auth-no-env"], "fix": ("config", "Set NEXTAUTH_SECRET (Auth.js: AUTH_SECRET) in the environment, never in client code."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c000000000037", "err": "RuntimeError: CUDA out of memory", "eco": "py", "rt": "py@3.12", "dep": ["torch"], "tried": ["batch-size-default"], "fix": ("constraint", "Lower batch size or run on CPU. Do not retry the same batch."), "eval": "true", "st": "confirmed", "nc": 11, "nf": 2},
    {"id": "spr_a11c000000000038", "err": "openai.BadRequestError: Error code: 400 - context_length_exceeded", "eco": "py", "rt": "py@3.12", "dep": ["openai@1.0.0"], "tried": ["full-history"], "fix": ("constraint", "Trim messages and tools until the prompt fits. Do not retry the same payload."), "eval": "true", "st": "confirmed", "nc": 14, "nf": 1},
    {"id": "spr_a11c000000000039", "err": "Error: spawn npx ENOENT", "eco": "mcp", "rt": "node@20", "dep": [], "tried": ["mcp-npx"], "fix": ("constraint", "npx is not on PATH for this process. Use an absolute node/npx path, then restart the MCP host."), "eval": "true", "st": "confirmed", "nc": 10, "nf": 0},
    {"id": "spr_a11c00000000003a", "err": "Unexpected token in JSON at position 0", "eco": "mcp", "rt": "node@20", "dep": [], "tried": ["mcp-stdio"], "fix": ("constraint", "MCP stdio must be JSON-RPC only. Print logs to stderr, never stdout."), "eval": "true", "st": "confirmed", "nc": 12, "nf": 1},
    {"id": "spr_a11c00000000003b", "err": "The term 'python3' is not recognized as the name of a cmdlet", "eco": "other", "rt": "windows", "dep": [], "tried": ["python3"], "fix": ("constraint", "On Windows the interpreter is usually python. Use py -3 or python, not python3."), "eval": "true", "st": "confirmed", "nc": 13, "nf": 0},
    {"id": "spr_a11c00000000003c", "err": "error: Microsoft Visual C++ 14.0 or greater is required", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["pip-install-c-ext"], "fix": ("constraint", "Install Microsoft C++ Build Tools, or use a wheel. Do not compile from source without MSVC."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 1},
    {"id": "spr_a11c00000000003d", "err": "UnicodeDecodeError: 'charmap' codec can't decode byte", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["open-default"], "fix": ("patch", "open(path, encoding='utf-8')  # Windows default is cp1252"), "eval": "true", "st": "confirmed", "nc": 11, "nf": 0},
    {"id": "spr_a11c00000000003e", "err": "AttributeError: 'Engine' object has no attribute 'execute'", "eco": "py", "rt": "py@3.12", "dep": ["sqlalchemy@2.0.0"], "tried": ["engine.execute"], "fix": ("patch", "with engine.connect() as conn: conn.execute(text(sql))  # SQLAlchemy 2"), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c00000000003f", "err": "RuntimeError: asyncio.run() cannot be called from a running event loop", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["asyncio.run-nested"], "fix": ("patch", "await the coroutine. Jupyter already has a loop; do not call asyncio.run inside it."), "eval": "true", "st": "confirmed", "nc": 10, "nf": 0},
    {"id": "spr_a11c000000000040", "err": "Error: MCP error -32602: Invalid params", "eco": "mcp", "rt": "node@20", "dep": [], "tried": ["tools-call"], "fix": ("constraint", "Tool arguments must match the schema. Fill required fields. Do not send a string where an object is required."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000041", "err": "anthropic.RateLimitError: Error code: 429", "eco": "py", "rt": "py@3.12", "dep": ["anthropic"], "tried": ["retry-immediate"], "fix": ("constraint", "Back off. Do not tight-loop the same request. Use retry-after if present."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 1},
    {"id": "spr_a11c000000000042", "err": "KeyError: 'OPENAI_API_KEY'", "eco": "py", "rt": "py@3.12", "dep": ["openai"], "tried": ["os.environ-bare"], "fix": ("constraint", "The process does not have OPENAI_API_KEY. Set it in the environment the agent actually runs in."), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c000000000043", "err": "TypeError: Object of type datetime is not JSON serializable", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["json.dumps"], "fix": ("patch", "json.dumps(obj, default=str) or datetime.isoformat()"), "eval": "true", "st": "confirmed", "nc": 10, "nf": 0},
    {"id": "spr_a11c000000000044", "err": "ReferenceError: process is not defined", "eco": "npm", "rt": "node@20", "dep": ["vite@5.0.0"], "tried": ["process.env-in-browser"], "fix": ("constraint", "Browser bundles have no process. Use import.meta.env (Vite) or NEXT_PUBLIC_ vars."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000045", "err": "Error: Could not find a production build in the '.next' directory", "eco": "npm", "rt": "node@20", "dep": ["next@15.0.0"], "tried": ["next-start-no-build"], "fix": ("cmd", "npx next build"), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c000000000046", "err": "sqlite3.OperationalError: database is locked", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["concurrent-writes"], "fix": ("constraint", "Another connection holds the write lock. Close it, or enable WAL. Do not retry in a tight loop."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 1},
    {"id": "spr_a11c000000000047", "err": "Activate.ps1 cannot be loaded because running scripts is disabled on this system", "eco": "other", "rt": "windows", "dep": [], "tried": ["venv-activate"], "fix": ("constraint", "Use .venv\\Scripts\\python.exe directly, or set ExecutionPolicy RemoteSigned for the current user."), "eval": "true", "st": "confirmed", "nc": 11, "nf": 0},
    {"id": "spr_a11c000000000048", "err": "fatal: not a git repository (or any of the parent directories): .git", "eco": "ci", "rt": "", "dep": [], "tried": ["git-status-wrong-dir"], "fix": ("constraint", "cwd is not a clone. cd to the repo root before git commands."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000049", "err": "error: failed to push some refs to", "eco": "ci", "rt": "", "dep": [], "tried": ["git-push"], "fix": ("constraint", "Remote has commits you do not. git pull --rebase (or fetch + rebase), then push. Do not --force a shared branch."), "eval": "true", "st": "confirmed", "nc": 9, "nf": 1},
    {"id": "spr_a11c00000000004a", "err": "Resource not accessible by integration", "eco": "ci", "rt": "", "dep": [], "tried": ["gh-actions-token"], "fix": ("constraint", "GITHUB_TOKEN lacks the permission. Grant contents/pull-requests/issues on the job, or use a PAT."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c00000000004b", "err": "bash: $'\\r': command not found", "eco": "ci", "rt": "", "dep": [], "tried": ["shell-script"], "fix": ("constraint", "CRLF line endings. Convert the script to LF. On checkout: git config core.autocrlf input."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c00000000004c", "err": "huggingface_hub.utils.HfHubHTTPError: 401 Client Error", "eco": "py", "rt": "py@3.12", "dep": ["huggingface_hub"], "tried": ["from_pretrained"], "fix": ("constraint", "Missing or invalid HF token. huggingface-cli login, or set HF_TOKEN."), "eval": "true", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c00000000004d", "err": "Can't resolve 'buffer' in", "eco": "npm", "rt": "node@20", "dep": ["webpack@5"], "tried": ["node-buffer"], "fix": ("constraint", "Webpack 5 dropped Node polyfills. Add resolve.fallback.buffer or stop importing Node libs in the browser."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c00000000004e", "err": "django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured", "eco": "py", "rt": "py@3.12", "dep": ["django"], "tried": ["import-models"], "fix": ("constraint", "Set DJANGO_SETTINGS_MODULE before importing Django models, or call django.setup()."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c00000000004f", "err": "Error: MCP error -32600: Invalid Request", "eco": "mcp", "rt": "node@20", "dep": [], "tried": ["tools-list-first"], "fix": ("constraint", "Send initialize (and initialized notification) before tools/list or tools/call."), "eval": "true", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c000000000050", "err": "uv: No solution found when resolving dependencies", "eco": "py", "rt": "py@3.12", "dep": ["uv"], "tried": ["uv-add"], "fix": ("constraint", "Two packages pin incompatible versions. Relax a pin, or drop one of the packages. CrewAI vs langchain-openai is a common pair."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 1},
    {"id": "spr_a11c000000000051", "err": "fatal: Unable to create '.git/index.lock': File exists.", "eco": "ci", "rt": "", "dep": [], "tried": ["git-add-parallel"], "fix": ("constraint", "Another git process holds index.lock. Wait for it, or delete .git/index.lock only if no git process is running."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000052", "err": "Error: ENOENT: no such file or directory, uv_cwd", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["cwd-deleted"], "fix": ("constraint", "The process cwd was deleted. cd to a directory that still exists, then retry."), "eval": "true", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c000000000053", "err": "ModuleNotFoundError: No module named 'pkg_resources'", "eco": "py", "rt": "py@3.12", "dep": [], "tried": ["import pkg_resources"], "fix": ("pin", "pip install setuptools"), "eval": "true", "st": "confirmed", "nc": 9, "nf": 0},
    {"id": "spr_a11c000000000054", "err": "RuntimeError: Working outside of application context", "eco": "py", "rt": "py@3.12", "dep": ["flask"], "tried": ["current_app"], "fix": ("patch", "Use the app context: with app.app_context(): ..."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000055", "err": "google.api_core.exceptions.ResourceExhausted: 429", "eco": "py", "rt": "py@3.12", "dep": ["google-generativeai"], "tried": ["retry-immediate"], "fix": ("constraint", "Quota. Back off. Do not tight-loop. Switch model or billing if the quota is exhausted."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 1},
    {"id": "spr_a11c000000000056", "err": "Error: Cannot find module 'sharp'", "eco": "npm", "rt": "node@20", "dep": ["next@15.0.0"], "tried": ["next-image"], "fix": ("pin", "npm install sharp  # required for next/image in standalone/CI"), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c000000000057", "err": "error TS2304: Cannot find name 'React'", "eco": "npm", "rt": "node@20", "dep": ["typescript@5.6.0"], "tried": ["react-without-types"], "fix": ("config", "jsx: react-jsx, and install @types/react. Do not prefix every JSX file with import React from 'react' unless jsx is react."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000058", "err": "npm error code ETARGET", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["npm-install-exact"], "fix": ("constraint", "No published version matches the range. Relax the version, or the package name is wrong."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c000000000059", "err": "Ollama: model not found", "eco": "other", "rt": "", "dep": ["ollama"], "tried": ["chat-missing-model"], "fix": ("constraint", "The model is not on disk. ollama pull <name>, then retry. Do not change the name and hope."), "eval": "true", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c00000000005a", "err": "There isn't a GitHub Pages site here.", "eco": "other", "rt": "", "dep": [], "tried": ["disable-pages"], "fix": ("constraint", "DNS still points at GitHub Pages after Pages was disabled. Remove the CNAME file, delete GitHub A/AAAA and www CNAME to github.io, point at the real host."), "eval": "true", "st": "confirmed", "nc": 2, "nf": 0},
    {"id": "spr_a11c00000000005b", "err": "Error: getaddrinfo ENOTFOUND", "eco": "npm", "rt": "node@20", "dep": [], "tried": ["fetch-bad-host"], "fix": ("constraint", "DNS failed for the hostname. Check the URL, VPN, and whether the host exists. Do not retry the same name in a tight loop."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c00000000005c", "err": "Error: connect ECONNREFUSED 127.0.0.1:5432", "eco": "other", "rt": "", "dep": ["postgres"], "tried": ["app-before-db"], "fix": ("constraint", "Nothing is listening on that port. Start Postgres, or point DATABASE_URL at a host that is actually up."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 0},
    {"id": "spr_a11c00000000005d", "err": "ENOSPC: no space left on device", "eco": "other", "rt": "", "dep": [], "tried": ["npm-install"], "fix": ("constraint", "The disk is full. Free space (node_modules, Docker images, /tmp). Do not retry until df shows room."), "eval": "true", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c00000000005e", "err": "Permission denied (publickey)", "eco": "ci", "rt": "", "dep": [], "tried": ["git-push-ssh"], "fix": ("constraint", "No SSH key is loaded for this host. ssh-add the key, or use HTTPS with a credential helper. Do not disable host key checking."), "eval": "true", "st": "confirmed", "nc": 9, "nf": 1},
    {"id": "spr_a11c00000000005f", "err": "error: pathspec did not match any file(s) known to git", "eco": "ci", "rt": "", "dep": [], "tried": ["git-checkout-typo"], "fix": ("constraint", "That path or branch does not exist in this clone. git status / git branch -a, then use a name that is actually there."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000060", "err": "Cannot use JSX unless the '--jsx' flag is provided", "eco": "npm", "rt": "node@20", "dep": ["typescript@5.6.0"], "tried": ["tsx-without-jsx"], "fix": ("config", "compilerOptions.jsx = 'react-jsx' in tsconfig. Include the file in tsconfig include."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c000000000061", "err": "Error: Cannot find native binding", "eco": "npm", "rt": "node@20", "dep": ["@swc/core"], "tried": ["npm-install"], "fix": ("constraint", "Optional native binary missing for this platform. Reinstall the package on this OS/arch, or delete node_modules and lockfile then npm ci."), "eval": "true", "st": "confirmed", "nc": 5, "nf": 1},
    {"id": "spr_a11c000000000062", "err": "API rate limit exceeded", "eco": "ci", "rt": "", "dep": [], "tried": ["gh-api-loop"], "fix": ("constraint", "GitHub unauthenticated limit is tiny. Set GH_TOKEN / a PAT, and back off. Do not tight-loop /repos."), "eval": "true", "st": "confirmed", "nc": 8, "nf": 1},
    {"id": "spr_a11c000000000063", "err": "Error: spawn git ENOENT", "eco": "ci", "rt": "", "dep": [], "tried": ["git-not-on-path"], "fix": ("constraint", "git is not on PATH for this process. Install Git and restart the agent host so PATH is reloaded."), "eval": "true", "st": "confirmed", "nc": 7, "nf": 0},
    {"id": "spr_a11c000000000064", "err": "Unable to locate credentials", "eco": "other", "rt": "", "dep": ["boto3"], "tried": ["aws-sdk"], "fix": ("constraint", "No AWS credentials in this process. Set AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY or a profile, in the environment the agent actually runs."), "eval": "true", "st": "confirmed", "nc": 6, "nf": 0},
    {"id": "spr_a11c000000000065", "err": "xcrun: error: invalid active developer path", "eco": "other", "rt": "macos", "dep": [], "tried": ["git-mac"], "fix": ("constraint", "Xcode CLT path is stale after an OS update. xcode-select --install, then retry."), "eval": "true", "st": "confirmed", "nc": 5, "nf": 0},
    {"id": "spr_a11c000000000066", "err": "fatal: refusing to merge unrelated histories", "eco": "ci", "rt": "", "dep": [], "tried": ["git-pull"], "fix": ("constraint", "The branches do not share a commit. Confirm they are the same project before --allow-unrelated-histories. Usually you cloned the wrong remote."), "eval": "true", "st": "confirmed", "nc": 4, "nf": 1},
]


def materialize() -> list[Claim]:
    out: list[Claim] = []
    for raw in _SEEDS:
        err = raw["err"]
        cls = classify(err)
        dep = list(raw.get("dep") or [])
        eco = raw.get("eco") or "other"
        rt = raw.get("rt") or ""
        k, b = raw["fix"]
        out.append(Claim(
            id=raw["id"],
            fp=fingerprint(err=err, cls=cls, eco=eco, rt=rt, dep=dep),
            cls=cls, err=normalize_error(err), eco=eco, rt=rt, dep=dep,
            tried=list(raw.get("tried") or []),
            fix=Fix(k=k, b=b), eval=EvalSpec(cmd=raw["eval"]),
            st=raw.get("st") or "proposed", nc=int(raw.get("nc") or 0), nf=int(raw.get("nf") or 0),
            own="did:claimidx:seed", ts=_TS, note=raw.get("note") or "", src="seed",
        ))
    return out
